### json-request

# curl -X GET http://localhost:8080/vehicle
GET http://localhost:8080/vehicle/23
Accept: application/json

### xml-request

GET http://localhost:8080/vehicle/24
Accept: application/xml

### JsonObject

GET http://localhost:8080/vehicle/json
Accept: application/json

### Response

GET http://localhost:8080/vehicle/response
Accept: application/json

### POST

POST http://localhost:8080/vehicle
Content-Type: application/json

{
  "brand": "Opel",
  "model": "Kapitän"
}

###

GET http://localhost:8080/vehicle
Accept: application/json

###